# Generated by Django 5.2.7 on 2025-10-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habitsapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="reward",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="habit",
            name="time",
            field=models.TimeField(help_text="Время когда нужно напомнить"),
        ),
    ]
