# Generated by Django 5.2.7 on 2025-10-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habitsapp", "0002_alter_habit_reward_alter_habit_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="duration_seconds",
            field=models.PositiveSmallIntegerField(
                default=60,
                help_text="Время выполнения должно быть не больше 120 секунд",
            ),
        ),
    ]
