# Generated by Django 5.2.7 on 2025-11-06 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("telegramapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="telegrammessage",
            old_name="message_tex",
            new_name="message_text",
        ),
    ]
