# Generated by Django 5.2.7 on 2025-11-06 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("telegramapp", "0002_rename_message_tex_telegrammessage_message_text"),
    ]

    operations = [
        migrations.RenameField(
            model_name="telegrammessage",
            old_name="is_send",
            new_name="is_sent",
        ),
    ]
